name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14  # Sürüm numarasını belirtin (örneğin, 14.x)
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org/'  # Özel registry kullanıyorsanız bunu ayarlayabilirsiniz

    - name: Set npm version
      run: npm install -g npm@9.8.1

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build --if-present

    - name: Run tests
      run: npm test

    - name: Create .env file
      run: |
        touch .env
        echo "${{ secrets.PROD_ENV_FILE }}" >> .env
